### PR TITLE
[5.15] Track Steam performance patches

### PR DESCRIPTION
**Pull request by kakra**
Export patch series: https://github.com/kakra/linux/pull/16.patch

### CODE REVIEW

**Comment by orbea** [comment]
@kakra Is there any information on usage for these patches? I enabled the winesync kernel module, but I am not sure what else needs to be done?

**Comment by kakra** [comment]
The winesync kernel module itself does nothing unless you also use the appropriate wine patches. There's very low activity around these patches, last time I looked at it, some commits still contained todo and fixme lines. It seems it has since been rebased. The patches should be here: https://repo.or.cz/wine/zf.git/shortlog/refs/heads/fastsync3

This is the commit, that actually opens the winesync device: https://repo.or.cz/wine/zf.git/commitdiff/85481c0a11baabc529c252fd36e58ee9e626860d (search for `/dev/winesync`) ... just to identify we are using the correct fastsync branch. The other patches following it will be needed, too, and the previous patch.

I don't think that any of the major protonized wine distributions currently include these patches so you'd need to rebase the patchset yourself. They'll conflict with esync and fsync so you'd need to either remove those, or integrate it properly (those conflicts should be easy to resolve, just take care to enable winesync with highest priority when detected, rebuilding of the wineserver protocol headers will be needed after resolving conflicts).

It looks like Tkg has limited support for it but it's not enabled by default: https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git/wine-tkg-patches/misc/fastsync

So with the kernel module enabled, you may receive better support from Tkg on how to actually make use of the module in wine.

Since winesync is still in very early (and silent) stages, I do not currently look into updates for the kernel module, it might be out of date. But I don't think there have been any critical updates to it. If you find evidence for a new kernel patch revision, let me know, and I'd happily update this patchset.

**Comment by orbea** [comment]
Thank you, that is useful information. The xanmod project also seems to have kernel patches for winesync, but I haven't compared the patches with what is here.

https://xanmod.org/

If none of the major proton wine builds are using these patches how does this PR relate to steam? Maybe there is something else I missed?

**Comment by kakra** [comment]
I just collect patches somehow related to my Steam installation here... It'll also improve non-Steam gaming probably. It's just a personal preference, and I had to give it a name. OTOH, we have to consider that these changes were mostly pushed by Valve activities (directly and indirectly) - so this gives "Steam" some credit for it. ;-)

**Comment by kakra** [comment]
I'm using sets of patches for different systems, this is one of the kernel patchsets I'm using for the system that has Steam installed - maybe take it that way... ;-)

**Comment by orbea** [comment]
That makes sense, thanks for explaining! I'm not sure how much time I will spend getting winesync to work right now, but I'll update here if I have any more information. :)

**Pull request closed without merging**
