### PR TITLE
[6.1] Track Steam performance patches

### PR DESCRIPTION
**Pull request by kakra**
Export patch series: https://github.com/kakra/linux/pull/23.patch

- **winesync:** experimental winesync device driver which can be used by some Proton versions
- **hugepages background reclaim:** patch cherry-picked from ZEN
- **threaded IRQs by default:** cherry-picked from CK
- **always use bfq IO scheduler by default:** although it might benchmark lower throughput it is almost always better for more consistent desktop IO latency during high IO write loads
- **memory soft-dirty flag:** used by Proton to support Windows memory write monitoring with better performance
- **ACS patch:** for whoever may need it, patch may be dropped at any time
- **futex backward compatibility patch:** Properly supports older Proton versions using the latest futex kernel functions
- **lower latency scheduling:** CFS patches cherry-picked and combined from TKG, Pop! OS and PF
- **memory management:** improved scheduling for huge memory pages and memory zones, cherry-picked from ZEN
- **readahead patches:** IO readahead raised to 2 MB to match huge pages, cherry-picked from XANMOD
- **raised vm.max_map_count:** as suggested by Valve (in Steam Deck) and TKG, cherry-picked from TKG

Many patches are enabled unconditionally, e.g., there's no config flag to enable ZEN patches as in their original patchset. This is because there's no point otherwise in using this patchset for me.

### CODE REVIEW

**Comment by orbea** [comment]
@kakra This doesn't apply against a `6.1.18` kernel from kernel.org, am I missing something?

**Comment by kakra** [comment]
@orbea Maybe, my distribution doesn't have kernel 6.1.18 yet, so I didn't try. I'm on 6.17. I'll bump the base-6.1 branch when I'm seeing conflicts.

But I just checked: 6.1.18 is available since today, so stay tuned.

**Comment by kakra** [comment]
Yep, confirmed: The conflict is in the ACS patch because a new PCIe quirk has been added. Easy fix, new patchset will be available once I rebooted with the patched kernel.

**Comment by kakra** [comment]
@orbea Bumped to 6.1.18

**Comment by kakra** [comment]
New patches added for better scheduling, memory, and IO latency. This also improves compatibility with some demanding games like Detroit: Become Human by raising `vm.max_map_count` by default, similar to what Valve does on the Steam Deck.

**Comment by kakra** [comment]
Rebased to #30

**Pull request closed without merging**
